{% set name = "django-typed-models" %}
{% set version = "0.15.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 4b3b3de58928946d8eaafc107576302ef07cba6dd309f241bccbeec45ab27127

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - django-stubs-ext
    - typing_extensions
    - python >={{ python_min }}
    - django
    - setuptools

test:
  imports:
    - typedmodels
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: http://github.com/craigds/django-typed-models
  summary: Sane single table model inheritance for Django
  license: BSD-3-Clause
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - ocefpaf
    - kwilcox
